spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
       ddl-auto: update
    properties:
       hibernate:
          format_sql: true
          show_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

jwt:
  secret: ${JWT_SECRET}