spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/til?serverTimezone=Asia/Seoul
    username: root
  jpa:
    hibernate:
       ddl-auto: update
    properties:
       hibernate:
          format_sql: true
          show_sql: true
  security:
      oauth2:
        client:
          registration:
            google:
              client-id:
              client-secret:
              scope:
                - profile
                - email

app:
    auth:
        tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
        tokenExpirationMsec: 864000000
    cors:
        allowedOrigins: http://localhost:3000,http://localhost:8080
    oauth2:
        authorizedRedirectUris:
            - http://localhost:3000/oauth2/redirect
